In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("Diamonds.csv")
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [24]:
#IQP
Q1 = df['carat'].quantile(0.25)
Q3 = df['carat'].quantile(0.75)
IQR = Q3-Q1
print(Q1, Q3, IQR)
low_ = Q1 - (1.5 * IQR) # 하한
up_ = Q3 + (1.5 * IQR) # 상한

0.4 1.04 0.64

In [15]:
# 이상치 값 찾기 
df_1 = df[ (df['carat']<low_) | (df['carat']>up_) ]
df_1

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
12246,12247,2.06,Premium,J,I1,61.2,58.0,5203,8.10,8.07,4.95
13002,13003,2.14,Fair,J,I1,69.4,57.0,5405,7.74,7.70,5.36
13118,13119,2.15,Fair,J,I1,65.5,57.0,5430,8.01,7.95,5.23
13757,13758,2.22,Fair,J,I1,66.7,56.0,5607,8.04,8.02,5.36
13991,13992,2.01,Fair,I,I1,67.4,58.0,5696,7.71,7.64,5.17
...,...,...,...,...,...,...,...,...,...,...,...
27741,27742,2.15,Ideal,G,SI2,62.6,54.0,18791,8.29,8.35,5.21
27742,27743,2.04,Premium,H,SI1,58.1,60.0,18795,8.37,8.28,4.84
27744,27745,2.29,Premium,I,SI1,61.8,59.0,18797,8.52,8.45,5.24
27746,27747,2.07,Ideal,G,SI2,62.5,55.0,18804,8.20,8.13,5.11
27749,27750,2.29,Premium,I,VS2,60.8,60.0,18823,8.50,8.47,5.16

In [ ]:
# 이상치를 제거한 데이터
delet_data = df[(df['carat']>=low_) & (df['carat']<=up_)]
delet_data

52051

In [25]:
# 상한, 하한값 출력
print(f'상한값: {up_}')
print(f'하한값: {low_}')
# 이상치를 제거한 데이터 개수 출력
len(delet_data)

상한값: 2.0
하한값: -0.5599999999999999

52051